#pragma once
static const char CONFIG_JSON[] =
"{\n"
"    \"provider_choice\": \"official\",\n"
"    \"provider\": {\n"
"        \"official\": {\n"
"            \"base_url\": \"https://api.deepseek.com/chat/completions\",\n"
"            \"api_key\":  \"\",\n"
"            \"model\": {\n"
"                \"flash\": \"deepseek-v4-flash\",\n"
"                \"pro\": \"deepseek-v4-pro\"\n"
"            }\n"
"        },\n"
"        \"volcano\": {\n"
"            \"base_url\": \"https://ark.cn-beijing.volces.com/api/v3/chat/completions\",\n"
"            \"api_key\":  \"\",\n"
"            \"model\": {\n"
"                \"r1\": \"deepseek-r1-250528\",\n"
"                \"v3\": \"deepseek-v3-2-251201\"\n"
"            }\n"
"        },\n"
"        \"local\": {\n"
"            \"base_url\": \"http://localhost:11434/api/generate\",\n"
"            \"model\": {\n"
"                \"r1\": \"deepseek-r1:14b\"\n"
"            }\n"
"        }\n"
"    },\n"
"    \"model_choice\": \"flash\",\n"
"    \"tool_choice\": \"none\",\n"
"    \"prompt\":  \"请使用中文回答\",\n"
"    \"thinking\": \"disabled\",\n"
"    \"reasoning_effort\": \"high\",\n"
"    \"temperature\": 1,\n"
"    \"max_tokens\": 393216,\n"
"    \"stream\": true,\n"
"    \"include_usage\": false\n"
"}\n"
"";
