#pragma once
static const char TOOL_CALLS_JSON[] =
"[\n"
"    {\n"
"        \"type\": \"function\",\n"
"        \"function\": {\n"
"            \"name\": \"get_cwd\",\n"
"            \"description\": \"Get current working directory.\",\n"
"            \"parameters\": {\n"
"                \"type\": \"object\",\n"
"                \"properties\": {},\n"
"                \"required\": []\n"
"            }\n"
"        }\n"
"    }, {\n"
"        \"type\": \"function\",\n"
"        \"function\": {\n"
"            \"name\": \"list_dir\",\n"
"            \"description\": \"Get the files in a directory.\",\n"
"            \"parameters\": {\n"
"                \"type\": \"object\",\n"
"                \"properties\": {\n"
"                    \"dir_path\": {\n"
"                        \"type\": \"string\",\n"
"                        \"description\": \"the directory path which you want to list files of.\"\n"
"                    }\n"
"                },\n"
"                \"required\": [\"dir_path\"]\n"
"            }\n"
"        }\n"
"    }, {\n"
"        \"type\": \"function\",\n"
"        \"function\": {\n"
"            \"name\": \"make_file\",\n"
"            \"description\": \"create file in the directory, directory will be automatically created recursively.\",\n"
"            \"parameters\": {\n"
"                \"type\": \"object\",\n"
"                \"properties\": {\n"
"                    \"dir_path\": {\n"
"                        \"type\": \"string\",\n"
"                        \"description\": \"the directory path which you want create file in.\"\n"
"                    },\n"
"                    \"filename\": {\n"
"                        \"type\": \"string\",\n"
"                        \"description\": \"the file you want to create in the directory.\"\n"
"                    }\n"
"                },\n"
"                \"required\": [\"dir_path\", \"filename\"]\n"
"            }\n"
"        }\n"
"    }\n"
"]";
